### ISSUE TITLE
Open stuck on "Initializing map cache"

### ISSUE THREAD

**Issue by SamPro910** [BlueRaja/Starbank#9]
The opening of a file is stuck on the process above, and it throws an error.

**Comment by BlueRaja** [comment]
It's not possible for me to look into this without some sort of error message or, preferably, repro steps.

It's most likely due to a certain map in your cache. What are the maps you played most recently? Did it work before then? Deleting maps from the cache until it no longer happens could narrow down the cause.

**Comment by SamPro910** [comment]
SOLVED: 
It WAS a certain map, unfortunately we don't know the name of it.
Remove the bank files of suspicious/all maps.

**Comment by cristian-dan-f** [comment]
this is still a continued problem, and it happens quite a lot!
Please make it ignore the problematic bank/map cache files instead of completely crashing. If for some reason loading a file causes an error, just skip and continue loading others.
Clearing the cache of maps makes the list of bank files empty.
